apiVersion: v1
data:
  POP_DB_HOST: "pop-rw.citypost.us"
  POP_DB_PORT: "5432"
  POP_DB_USER: "postgres"
  POP_DB_PASSWORD: "Asterisk@123"
  POP_DB_NAME: "pop"
  RATE_LIMIT_WINDOW_SECONDS: "1"
  RATE_LIMIT_MAX: "50"
kind: ConfigMap
metadata:
  name: pop-api
  namespace: backend
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pop-api
  namespace: backend
  labels:
    app: pop-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pop-api
  template:
    metadata:
      labels:
        app: pop-api
        version: v0.0.1
    spec:
      containers:
      - name: pop-api
        image: smartcitymedia/pop-app:0.0.14
        envFrom:
          - configMapRef:
              name: pop-api
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: scm-registrypullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: pop-api
  namespace: backend
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 8080
  selector:
    app: pop-api
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pop-api
  namespace: backend
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`pop-api.citypost.us`)
      kind: Rule
      services:
        - name: pop-api
          port: 8080
  tls:
    secretName: traefik-cert